#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "omniai/openai"

client = OmniAI::OpenAI::Client.new

puts "> [SYSTEM] Respond in both English and French."
puts "> [USER] What is the fastest animal?"

client.chat(stream: $stdout) do |prompt|
  prompt.system "Respond in both English and French."
  prompt.user "What is the fastest animal?"
end
