#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "omniai/openai"

CLIENT = OmniAI::OpenAI::Client.new

puts "> [USER] Tell me a joke"

response = CLIENT.chat("Tell me a joke")
puts response.text
